# Generated by Django 5.1.4 on 2026-01-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_agentchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentchat',
            name='task_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
