# Generated by Django 5.1.4 on 2026-01-27 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agentchat_task_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('description', models.TextField(help_text='What the client initially wanted')),
                ('followup_notes', models.TextField(blank=True, help_text='What the client said after contact')),
                ('status', models.CharField(choices=[('project', 'Converted to Project'), ('held', 'On Hold'), ('rejected', 'Rejected')], default='held', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_leads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
