# Generated by Django 5.1.4 on 2026-01-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clientlead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
