# Generated by Django 5.1.4 on 2026-01-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_task_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlead',
            name='description',
            field=models.TextField(blank=True, help_text='What the client initially wanted', null=True),
        ),
        migrations.AlterField(
            model_name='clientlead',
            name='followup_notes',
            field=models.TextField(blank=True, help_text='What the client said after contact', null=True),
        ),
        migrations.AlterField(
            model_name='clientlead',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientlead',
            name='status',
            field=models.CharField(choices=[('new', 'New Lead'), ('project', 'Converted to Project'), ('held', 'On Hold'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
